version: '3.1'

services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html/

  db:
    container_name: appDB
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    restart: always
    environment:
      MYSQL_DATABASE: userlistdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php


volumes:
  mysql-data:
